#!/bin/zsh

basetag="trieloff/"
tag="githop"

if [[ "$1" == .* ]]; then
	tag="${tag}${1#.}"
	shift
fi
if [[ "$1" == :* ]]; then
	tag="${basetag}${tag}${1}"
	shift
fi

echo $tag

name=$(echo $1 | sed -e "s/.*\\///" | sed -e "s/\\.git$//")

dockers=$(docker ps | wc -l | sed -e "s/ //g")

CONTAINER=$(docker run -p ${dockers}548:548 -it -d ${tag})
echo "Started $CONTAINER"

if [ $(uname) = "Darwin" ]; then
	echo "Setting up AFP daemon"

	docker exec $CONTAINER sed -i "10s/.*/[${name}]/" /etc/afp.conf
	docker exec $CONTAINER sed -i "11s|.*|path = /code/${name}|" /etc/afp.conf
	docker exec $CONTAINER sed -i "16s/.*/valid users = afp/" /etc/afp.conf

	echo "Creating Login User"
	echo "afp:$CONTAINER" | docker exec -i $CONTAINER chpasswd
	docker exec $CONTAINER chown -R afp /code

	echo "Starting AFP daemon"

	docker exec $CONTAINER netatalk
	
	#docker exec $CONTAINER /docker-entrypoint.sh
fi

echo "Copying essential files"
docker cp ~/.ssh/id_rsa $CONTAINER:/root/.ssh/id_rsa
docker cp ~/.m2/settings.xml $CONTAINER:/root/.m2/settings.xml
docker cp ~/.ssh/known_hosts $CONTAINER:/root/.ssh/known_hosts
docker cp ~/.gitconfig $CONTAINER:/root/.gitconfig

docker cp ~/.ssh/id_rsa $CONTAINER:/code/.ssh/id_rsa
docker cp ~/.m2/settings.xml $CONTAINER:/code/.m2/settings.xml
docker cp ~/.ssh/known_hosts $CONTAINER:/code/.ssh/known_hosts
docker cp ~/.gitconfig $CONTAINER:/code/.gitconfig

docker exec $CONTAINER chown -R afp /code

echo "Checking out repos in container"
docker exec $CONTAINER /usr/bin/githop $@

if [ $(uname) = "Darwin" ]; then
	mkdir -p $name
	echo "Mounting Evide^H Workspace"

	echo mount_afp afp://afp:${CONTAINER}@localhost:${dockers}548/${name} ${name}
	mount_afp afp://afp:${CONTAINER}@localhost:${dockers}548/${name} ${name}	
	
fi

echo "Logging into container"
docker attach $CONTAINER

echo "Killing container"
docker kill $CONTAINER

if [ $(uname) = "Darwin" ]; then

	echo "Unmounting Workspace"
	diskutil unmount force $name &
	rm -r $name

fi

echo "Done."