#!/bin/zsh
echo "Getting Repos from Git"

mkdir -p /code

cd /code
#git clone $1

reponame=$(echo $1 | sed -e "s/.*://" | sed -e "s/\\.git$//")
myname=$(echo $reponame | sed -e "s/^.*\\///")
user=$(echo $reponame | sed -e "s/\\/.*$//")
branch="master"

for repo in $@
do
	reponame=$(echo $repo | sed -e "s/.*://" | sed -e "s/\\.git$//")
	name=$(echo $reponame | sed -e "s/^.*\\///")
	user=$(echo $reponame | sed -e "s/\\/.*$//")

	
	if [[ "$repo" == :* ]]; then
		branch="${repo:1}"
	elif [ "$repo" = "$1" ]; then
		user="origin"
		su afp -c "git clone $repo"
		cd $name
	elif [ "$repo" = "$2" ]; then
		user="upstream"
		su afp -c "git remote add upstream $repo"
	else
		su afp -c "git remote add $user $repo"
	fi 
	#echo $reponame $name $user
done

su afp -c "git fetch --all"
su afp -c "git checkout ${branch}"
su afp -c "git submodule update --init --recursive"

chown -R afp /code