--- 
jobs: 
  build-base: 
    machine: true
    steps: 
      - checkout
      - 
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh Dockerfile
  build-java: 
    machine: true
    steps: 
      - checkout
      - 
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh java.Dockerfile
  build-clojure: 
    machine: true
    steps: 
      - checkout
      - 
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh clojure.Dockerfile
  build-clojurescript: 
    machine: true
    steps: 
      - checkout
      - 
        run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh clojurescript.Dockerfile
version: 2
workflows: 
  build: 
    jobs: 
      - build-base
      - build-java:
          requires: 
            - build-base
      - build-clojure:
          requires: 
            - build-java
      - build-clojurescript:
          requires: 
            - build-clojure
  version: 2
