--- 
jobs: 
  build-base: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh Dockerfile
  build-java: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh java.Dockerfile
  build-clojure: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh clojure.Dockerfile
  build-clojurescript: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh clojurescript.Dockerfile
  build-node: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh node.Dockerfile
  build-node8: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh node8.Dockerfile
  build-rust: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh rust.Dockerfile
  build-erlang: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh erlang.Dockerfile
  build-elixir: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh elixir.Dockerfile
  build-haskell: 
    machine: true
    steps: 
      - checkout
      - run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bash build.sh haskell.Dockerfile
version: 2
workflows: 
  build: 
    jobs: 
      - build-base
      - build-java:
          requires: 
            - build-base
      - build-clojure:
          requires: 
            - build-java
      - build-clojurescript:
          requires: 
            - build-clojure
      - build-node8:
          requires: 
            - build-base
      - build-node:
          requires: 
            - build-base
      - build-rust:
          requires: 
            - build-base
      - build-haskell:
          requires: 
            - build-base
      - build-erlang:
          requires: 
            - build-base
      - build-elixir:
          requires: 
            - build-erlang
  version: 2
